/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#13131b",
        "on-secondary-container": "#b7b5b4",
        "surface-container-lowest": "#0d0d15",
        "on-primary-container": "#0d0096",
        "inverse-surface": "#e4e1ed",
        "on-tertiary-fixed": "#301400",
        "surface-container-low": "#1b1b23",
        "secondary": "#c8c6c5",
        "background": "#13131b",
        "tertiary-container": "#d97721",
        "tertiary": "#ffb783",
        "surface-container-highest": "#34343d",
        "on-primary-fixed-variant": "#2f2ebe",
        "error-container": "#93000a",
        "on-primary": "#1000a9",
        "inverse-primary": "#494bd6",
        "primary": "#c0c1ff",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed": "#ffdcc5",
        "surface-bright": "#393841",
        "outline-variant": "#464554",
        "surface-container": "#1f1f27",
        "on-tertiary": "#4f2500",
        "surface-tint": "#c0c1ff",
        "secondary-container": "#474746",
        "outline": "#908fa0",
        "on-surface": "#e4e1ed",
        "on-background": "#e4e1ed",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#474746",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#452000",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-on-surface": "#303038",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1b1b1c",
        "surface-container-high": "#292932",
        "primary-container": "#8083ff",
        "tertiary-fixed-dim": "#ffb783",
        "surface-dim": "#13131b",
        "on-surface-variant": "#c7c4d7",
        "surface-variant": "#34343d",
        "on-error": "#690005",
        "on-secondary": "#303030"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "sm": "8px",
        "margin-mobile": "20px",
        "xs": "4px",
        "md": "16px",
        "lg": "24px",
        "2xl": "64px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "unit": "8px"
      },
      fontFamily: {
        "display-xl": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "label-sm": ["Geist"],
        "body-lg": ["Geist"]
      },
      fontSize: {
        "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}